### ISSUE TITLE
Possible new feature: JEI Integration

### ISSUE THREAD

**Issue by CalaMariGold** [CaliforniaDemise/Patchouli#1]
A lot of times I forget to check the guidebook about a certain item or feature as I'm scrolling through JEI, not to mention i don't know if this particular item even has a guidebook entry or where to find it (no search functionality in patchouli??). So, in CraftTweaker (or it's own config) you would correlate an item/block to a specific guidebook entry, so when you click on the guidebook JEI tab for X item, it auto opens the guidebook to the right page, effectively removing the need for many JEI descriptions.

**Comment by CaliforniaDemise** [comment]
I can try it

**Comment by Foreck1** [comment]
It would certainly be great. I can see an issue where multiple guidebooks (from other mods, for example) have entries for the same item. If this were to be added, I think a system to blacklist obsolete entries from certain books would be needed.

I propose a mockup for how this could work as well: 
![image](https://github.com/CaliforniaDemise/Patchouli/assets/47757429/ac3fb702-e9ad-47b1-95dc-726516114699)

**Comment by MasterEnderman** [comment]
With version 0.2.0 this is now a feature in my mod [Patchouli Books](https://www.curseforge.com/minecraft/mc-mods/patchouli-books/files/5895705). Any feedback is greatly appreciated.
